languageCode = "en"
languageName = "English"
label = "English"
weight = 1
title = "Delfi Sol Pandiani"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  description = "Broken Binaries ~ Delfi Sol Pandiani, Assistant Professor of Cultural Data Analysis at the University of Amsterdam."

[params.author]
  name = "Delfi Sol (Martinez) Pandiani"
  email = "d.s.martinezpandiani@uva.nl"
  headline = "Assistant Professor of Cultural Data Analysis | University of Amsterdam"
  bio = ""
  image = "img/delfi-sol-martinez-pandiani.png"
  links = [
    { gscholar = "https://scholar.google.com/citations?hl=en&user=aWasWbEAAAAJ" },
    { github = "https://github.com/delfimpandiani" },
    { linkedin = "https://www.linkedin.com/in/dmartinezpandiani/" },
    { email = "mailto:d.s.martinezpandiani@uva.nl" },
  ]
