colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = false

enableSearch = false
enableCodeCopy = true

mainSections = ["art", "research", "publications", "teaching"]

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = false

[homepage]
  layout = "profile"
  showRecent = false
  showRecentItems = 5
  showMoreLink = false
  cardView = false

[article]
  showDate = false
  showAuthor = false
  showHero = false
  showBreadcrumbs = false
  showDraftLabel = false
  showEdit = false
  showReadingTime = false
  showWordCount = false
  showTableOfContents = false

[list]
  showCards = false
  showBreadcrumbs = true
  showTableOfContents = false

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5
